### ISSUE TITLE
Review 0

### ISSUE THREAD

**Issue by VulpesCorsac** [Semyonov-as/Raytracing#1]
1. Better return T& and const T& - for x, y, z.
2. What will actually be returned as NULL in the [] operator? Throw exception (there is one just for the case). Same thing here - ref and const ref would be better.
3. -= operator?
4. Better separate declaration and definition (yes. they can be in a single file, but not so messy)
5. Better not to shorten names - if it is a Vector, then call it Vector, not Vec.
6. Blank lines. There is a mess in them (: 
7. Better put using in separate files as they can be used differently in other projects. Let's assume that you plan to use these files later.
8. Separate includes custom and standard headers by a blank line.
9. Single blank line after headers.
10. Space between include and bracket.

**Comment by Semyonov-as** [comment]
2, 3, 5, 8, 9, 10 - fixed

**Comment by Semyonov-as** [comment]
1, 7 - fixed

**Comment by Semyonov-as** [comment]
4 - fixed
